name: ${project.artifactId}
main: no.andy.firstspawn.FirstSpawn
version: ${project.version}
website: ${project.url}
author: andypandy89
description: ${project.description}
commands:
  firstspawn:
      description: FirstSpawn commands
      usage: /firstspawn help
permissions:
  firstspawn.set:
    description: Sets the spawn point for newcomers
  firstspawn.spawn:
    description: Allow players to spawn with /newspawn
  
