name: ${project.artifactId}
main: no.andy.firstspawn.FirstSpawn
version: ${project.version}
website: ${project.url}
author: andypandy89
description: ${project.description}
commands:
  firstspawn:
      description: FirstSpawn commands
      usage: /<command> help
permissions:
  firstspawn.set:
    description: Sets the spawn point for newcomers
  firstspawn.spawn:
    description: Allow players to spawn with /newspawn
  firstspawn.send:
    description: Allow sender to send others to /newspawn
  firstspawn.reload:
    description: Allow sender to reload configuration.
  firstspawn.override:
    description: Players with this permission-node will be ignored by FirstSpawn
  
